from engine.rakuten.rakuten_stock import detect_rakuten_stock
from engine.yahoo.yahoo_stock import detect_yahoo_stock
from engine.pokemoncenter.pokemon_stock import detect_pokemoncenter_stock
from engine.sevennet.sevennet_stock import detect_sevennet_stock


detect_rakuten_stock()
detect_yahoo_stock()
detect_pokemoncenter_stock
detect_sevennet_stock()